param1=10
for seed in 0 1 2 3 4 5 6 7 8 9
do
    for param2 in 5
    do
        # privilage
        # nohup python3 test_policy.py learning_progress/01-19-circle-peg-hole-pegangle-seed-$param1-$param2-$seed/latest.pt -n 01-19-circle-peg-hole-pegangle-seed-$param1-$param2-$seed --save True --param1 $param1 --param2 $param2 > nohup-circle-test-$seed.out &
        # python3 test_policy.py learning_progress/01-19-square-peg-hole-pegangle-seed-$param1-$param2-$seed/latest.pt -n 01-19-square-peg-hole-pegangle-seed-$param1-$param2-$seed --save True --param1 $param1 --param2 $param2 > nohup-square-test-$seed.out &
        # python3 test_policy.py learning_progress/01-19-triangle-peg-hole-pegangle-seed-$param1-$param2-$seed/latest.pt -n 01-19-triangle-peg-hole-pegangle-seed-$param1-$param2-$seed --save True --param1 $param1 --param2 $param2 > nohup-triangle-test-$seed.out &     
        # python3 test_policy.py learning_progress/01-19-rectangle-peg-hole-pegangle-seed-$param1-$param2-$seed/latest.pt -n 01-19-rectangle-peg-hole-pegangle-seed-$param1-$param2-$seed --save True --param1 $param1 --param2 $param2 > nohup-rectangle-test-$seed.out & 
        # tcn
        # nohup python3 test_policy_tcn.py learning_progress_tcn/01-21-tcn-circle-peg-hole-pegangle-$param1-$param2-$seed/iter10000.pt -n 02-07-tcn-circle-peg-hole-pegangle-$param1-$param2-$seed --save True --param1 $param1 --param2 $param2 > nohup-circle-test-$seed.out &
        # nohup python3 test_policy_tcn.py learning_progress_tcn/01-21-tcn-square-peg-hole-pegangle-$param1-$param2-$seed/iter10000.pt -n 01-21-tcn-square-peg-hole-pegangle-$param1-$param2-$seed --save True --param1 $param1 --param2 $param2 > nohup-square-test-$seed.out &
        # nohup python3 test_policy_tcn.py learning_progress_tcn/01-21-tcn-triangle-peg-hole-pegangle-$param1-$param2-$seed/iter10000.pt -n 01-21-tcn-triangle-peg-hole-pegangle-$param1-$param2-$seed --save True --param1 $param1 --param2 $param2 > nohup-triangle-test-$seed.out &     
        # nohup python3 test_policy_tcn.py learning_progress_tcn/01-21-tcn-rectangle-peg-hole-pegangle-$param1-$param2-$seed/iter10000.pt -n 01-21-tcn-rectangle-peg-hole-pegangle-$param1-$param2-$seed --save True --param1 $param1 --param2 $param2 > nohup-rectangle-test-$seed.out &  
        # noalignment
        # python3 test_policy.py learning_progress/01-19-circle-noalignment-peg-hole-pegangle-seed-$param1-$param2-$seed/latest.pt -n 01-19-circle-noalignment-peg-hole-pegangle-seed-$param1-$param2-$seed --save True --param1 $param1 --param2 $param2 > nohup-circle-test-$seed.out &
        # python3 test_policy.py learning_progress/01-19-square-noalignment-peg-hole-pegangle-seed-$param1-$param2-$seed/latest.pt -n 01-19-square-noalignment-peg-hole-pegangle-seed-$param1-$param2-$seed --save True --param1 $param1 --param2 $param2 > nohup-square-test-$seed.out &
        # python3 test_policy.py learning_progress/01-19-triangle-noalignment-peg-hole-pegangle-seed-$param1-$param2-$seed/latest.pt -n 01-19-triangle-noalignment-peg-hole-pegangle-seed-$param1-$param2-$seed --save True --param1 $param1 --param2 $param2 > nohup-triangle-test-$seed.out &     
        # python3 test_policy.py learning_progress/01-19-rectangle-noalignment-peg-hole-pegangle-seed-$param1-$param2-$seed/latest.pt -n 01-19-rectangle-noalignment-peg-hole-pegangle-seed-$param1-$param2-$seed --save True --param1 $param1 --param2 $param2 > nohup-rectangle-test-$seed.out & 
        # student
        # nohup python3 test_student.py -p learning_progress/01-19-circle-peg-hole-pegangle-seed-$param1-$param2-$seed/latest.pt -s student_progress/02-07-circle-peg-hole-pegangle-seed-$param1-$param2-$seed-student/iter8000.pt -n 02-07-circle-peg-hole-pegangle-seed-$param1-$param2-$seed-student --save True --param1 $param1 --param2 $param2 & 
        # nohup python3 test_student.py -p learning_progress/01-19-square-peg-hole-pegangle-seed-$param1-$param2-$seed/latest.pt -s student_progress/02-07-square-peg-hole-pegangle-seed-$param1-$param2-$seed-student/iter5000.pt -n 02-07-square-peg-hole-pegangle-seed-$param1-$param2-$seed-student --save True --param1 $param1 --param2 $param2 &
        # nohup python3 test_student.py -p learning_progress/01-19-triangle-peg-hole-pegangle-seed-$param1-$param2-$seed/latest.pt -s student_progress/02-07-triangle-peg-hole-pegangle-seed-$param1-$param2-$seed-student/iter5000.pt -n 02-07-triangle-peg-hole-pegangle-seed-$param1-$param2-$seed-student --save True --param1 $param1 --param2 $param2 &
        # nohup python3 test_student.py -p learning_progress/01-19-rectangle-peg-hole-pegangle-seed-$param1-$param2-$seed/latest.pt -s student_progress/02-07-rectangle-peg-hole-pegangle-seed-$param1-$param2-$seed-student/iter5000.pt -n 02-07-rectangle-peg-hole-pegangle-seed-$param1-$param2-$seed-student --save True --param1 $param1 --param2 $param2 &
        # student generalozation
        python3 test_student.py -p learning_progress/01-19-circle-peg-hole-pegangle-seed-$param1-$param2-$seed/latest.pt -s student_progress/01-28-circle-peg-hole-pegangle-seed-$param1-$param2-$seed-student/iter5000.pt -n 02-05-circle-circle-peg-hole-pegangle-seed-$param1-$param2-$seed-student  --save True --param1 $param1 --param2 $param2 & 
        # nohup python3 test_student.py -p learning_progress/01-19-circle-peg-hole-pegangle-seed-$param1-$param2-$seed/latest.pt -s student_progress/01-28-circle-peg-hole-pegangle-seed-$param1-$param2-$seed-student/iter5000.pt -n 02-05-circle-square-peg-hole-pegangle-seed-$param1-$param2-$seed-student --save True --param1 $param1 --param2 $param2 &
        # nohup python3 test_student.py -p learning_progress/01-19-circle-peg-hole-pegangle-seed-$param1-$param2-$seed/latest.pt -s student_progress/01-28-circle-peg-hole-pegangle-seed-$param1-$param2-$seed-student/iter5000.pt -n 02-05-circle-triangle-peg-hole-pegangle-seed-$param1-$param2-$seed-student --save True --param1 $param1 --param2 $param2 &
        # nohup python3 test_student.py -p learning_progress/01-19-circle-peg-hole-pegangle-seed-$param1-$param2-$seed/latest.pt -s student_progress/01-28-circle-peg-hole-pegangle-seed-$param1-$param2-$seed-student/iter5000.pt -n 02-05-circle-rectangle-peg-hole-pegangle-seed-$param1-$param2-$seed-student --save True --param1 $param1 --param2 $param2 &
        # tcn generalozation
        # nohup python3 test_policy_tcn.py learning_progress_tcn/02-07-tcn-circle-peg-hole-pegangle-$param1-$param2-$seed/iter10000.pt -n 02-07-tcn-circle-circle-peg-hole-pegangle-seed-$param1-$param2-$seed --save True --param1 $param1 --param2 $param2 & 
        # nohup python3 test_policy_tcn.py learning_progress_tcn/02-07-tcn-circle-peg-hole-pegangle-$param1-$param2-$seed/iter10000.pt -n 02-07-tcn-circle-square-peg-hole-pegangle-seed-$param1-$param2-$seed --save True --param1 $param1 --param2 $param2 &
        # nohup python3 test_policy_tcn.py learning_progress_tcn/02-07-tcn-circle-peg-hole-pegangle-$param1-$param2-$seed/iter10000.pt -n 02-07-tcn-circle-triangle-peg-hole-pegangle-seed-$param1-$param2-$seed --save True --param1 $param1 --param2 $param2 &
        # nohup python3 test_policy_tcn.py learning_progress_tcn/02-07-tcn-circle-peg-hole-pegangle-$param1-$param2-$seed/iter10000.pt -n 02-07-tcn-circle-rectangle-peg-hole-pegangle-seed-$param1-$param2-$seed --save True --param1 $param1 --param2 $param2 &
        # abration
        # nohup python3 test_policy.py learning_progress/02-13-circle-peg-hole-pegangle-seed-0-5-$seed/latest.pt -n 02-13-circle-peg-hole-pegangle-seed-0-5-$seed --save True --param1 $param1 --param2 $param2 > nohup-circle-test-$seed.out &
        # nohup python3 test_policy.py learning_progress/02-13-circle-peg-hole-pegangle-seed-10-0-$seed/latest.pt -n 02-13-circle-peg-hole-pegangle-seed-10-0-$seed --save True --param1 $param1 --param2 $param2 > nohup-circle-test-$seed.out &
        # nohup python3 test_policy.py learning_progress/02-13-circle-fixedstiffness-peg-hole-pegangle-seed-10-5-$seed/latest.pt -n 02-13-circle-fixedstiffness-peg-hole-pegangle-seed-10-5-$seed --save True --param1 $param1 --param2 $param2 > nohup-circle-test-$seed.out &
        # nohup python3 test_policy.py learning_progress/01-19-circle-noalignment-peg-hole-pegangle-seed-10-5-$seed/latest.pt -n 01-19-circle-noalignment-peg-hole-pegangle-seed-10-5-$seed --save True --param1 $param1 --param2 $param2 > nohup-circle-test-$seed.out &
        # student noalignment generalization
        # nohup python3 test_student.py -p learning_progress/01-19-circle-noalignment-peg-hole-pegangle-seed-$param1-$param2-$seed/latest.pt -s student_progress/01-28-circle-noalignment-peg-hole-pegangle-seed-$param1-$param2-$seed-student/iter5000.pt -n 02-05-circle-noalignment-circle-peg-hole-pegangle-seed-$param1-$param2-$seed-student --save True --param1 $param1 --param2 $param2 &
        # nohup python3 test_student.py -p learning_progress/01-19-circle-noalignment-peg-hole-pegangle-seed-$param1-$param2-$seed/latest.pt -s student_progress/01-28-circle-noalignment-peg-hole-pegangle-seed-$param1-$param2-$seed-student/iter5000.pt -n 02-05-circle-noalignment-square-peg-hole-pegangle-seed-$param1-$param2-$seed-student --save True --param1 $param1 --param2 $param2 &
        # nohup python3 test_student.py -p learning_progress/01-19-circle-noalignment-peg-hole-pegangle-seed-$param1-$param2-$seed/latest.pt -s student_progress/01-28-circle-noalignment-peg-hole-pegangle-seed-$param1-$param2-$seed-student/iter5000.pt -n 02-05-circle-noalignment-triangle-peg-hole-pegangle-seed-$param1-$param2-$seed-student --save True --param1 $param1 --param2 $param2 &
        # nohup python3 test_student.py -p learning_progress/01-19-circle-noalignment-peg-hole-pegangle-seed-$param1-$param2-$seed/latest.pt -s student_progress/01-28-circle-noalignment-peg-hole-pegangle-seed-$param1-$param2-$seed-student/iter5000.pt -n 02-05-circle-noalignment-rectangle-peg-hole-pegangle-seed-$param1-$param2-$seed-student --save True --param1 $param1 --param2 $param2 &
    done
done
